spring:
  application:
    name: legaltech-backend

  main:
    banner-mode: off

  security:
    user:
      name: holger
      password: QU11OWIz

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres